### ISSUE TITLE
Bounce endpoint fails to clear the cache when using Persistent Object Cache

### ISSUE THREAD

**Issue by ithielnor** [ownerrez/orez-wp#5]
Need to research. (REF: 117301)

Transients Manager shows:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/3342620/211035599-1776a588-e9e7-42b1-93f5-de4e551a2230.png">

**Comment by programcsharp** [comment]
Can we call wp_cache_delete: https://developer.wordpress.org/reference/classes/wp_object_cache/ in addition to delete_transient? That'd be a quick fix if it does solve the issue.
 
We should also put in an auto cache clear -- wouldn't be hard to have a background service that checks PCR change dates against a last cleared date on ExternalSite and triggers the existing cache clear method.

**Comment by ithielnor** [comment]
That's not enough. From the article:

> Use the [Transients API](https://developer.wordpress.org/apis/handbook/transients/) instead of these functions if you need to guarantee that your data will be cached. If persistent caching is configured, then the transients functions will use the wp_cache functions described in this document. However if persistent caching has not been enabled, then the data will instead be cached to the options table.

**Comment by ithielnor** [comment]
https://kellenmace.com/delete-transients-with-prefix-in-wordpress/

> ... If a persistent object cache is being used, transients are stored in memory rather than in the database, so trying to find them in the database won’t work. If you are using a persistent object cache, you should use the looping method described above, or something similar to construct all possible transient keys and call delete_transient() on each one.

Wow WordPress! That's just bad!

There literally is no way to surgically clear transients stored in the object cache short of looping through the whole cache!

I found this gist that keeps track of all the dynamic cache keys in the db so you can use that later to clear them... 😢 https://gist.github.com/kellenmace/578a7e2d83d8c007f16dc82987e8facb

**Comment by ithielnor** [comment]
Here's a pessimistic approach...

**Comment by programcsharp** [comment]
Oof. Yeah, I think that's fine for now since it only happens when you whack the button.

When we add auto invalidate, then maybe we want to track and clear only ours.
